bbatsov/helm-projectile

helm-projectile.el

helm-resume allows you to restore latest helm session.
When you try to restore after helm-projectile-grep, helm-restore uses
helm-sources-grep variable to get list of candidates. Hence
helm-source-grep must be used as global variable, to preserve list of
candidates for consecutive helm-resume.

Fix helm-resume for helm-projectile-grep

---

helm-projectile.el

So that I can invoke `helm-projectile-toggle` via `use-package` without "might not be defined at runtime" flycheck message.
Why not use `helm-projectile-on`? Because I do not want `(message "Turn on helm-projectile key bindings")` to run, and I'm not yet using Emacs 25 to use `inhibit-message`.
Thank you.

Add autoload to helm-projectile-toggle

---

helm-projectile.el

This is a suggestion / request to re-word the delete project command and make it consistent with existing label "Remove project(s) `M-D'".  "Delete" can be a dangerous verb and the description doesn't entirely preclude the possibility that files could be deleted.  I suggest "remove" with a slightly more verbose explanation of the action.
What do you think?  It does break the pure mnemonic `M-D', but that doesn't violate the aesthetic in my eyes.
Thanks for the package :-)  :+1:

Revise description for "delete project" command

---

helm-projectile.el

Hi,
When using `helm-projectile-grep`, I encountered a problem that Helm-Projectile still searches through directories which are ignored by Projectile (setting in the file .projectile). This problem was also discussed by an user in Stackexchange: http://emacs.stackexchange.com/questions/17801/projectile-grep-file-filter
After investigation, I figured out a possible reason is that Helm-Projectile get a list of ignored directories by invoking `(projectile-ignored-directories-rel)`. Names of directories returned by this function all contain a trailing forward slash `/`. If this trailing forward slash `/` is removed before assigned to the variable `helm-grep-ignored-directories`, then `helm-projectile-grep` will ignore these folders.
So, I'd like to ask if this is a root cause of the problem? …

remove trailing "/" in ignored directories so that Helm can recognize Projectile's configuration

---

helm-projectile.el

This PR makes it possible to customize the helm "actions" that are available when using `helm-projectile-grep`. So with this, one can add a new action as follows:
```emacs-lisp
(setq helm-projectile-grep-or-ack-actions
(append helm-projectile-grep-or-ack-actions
'("My new action"
my-new-action-function)))
```
AIUI it is not possible to use the usual helm API `helm-add-action-to-source`, because `helm-projectile-grep-or-ack` [overwrites](https://github.com/bbatsov/helm-projectile/blob/master/helm-projectile.el#L679) the source.

Allow grep actions to be customized

---

helm-projectile.el

@bbatsov suggested I create a pull request, since I suggested that `projectile-find-file-hook` should run when using `helm-projectile` to find files in projectile projects  #22. So here's an attempt to do just that :) It should work, but in some cases it may be possible that the hooks are run twice: Line 427 to 432; `make-dir-fn` runs the hooks, but then the hooks are run again, beacause the cases in the `cond` doesn't run the hooks.

projectile-find-file-hook runs when finding-file.

---

helm-projectile.el

Address #56 by using `helm-projectile-file-persistent-action` where derivatives of `helm-find-files-action` are used.

Preview instead of find file with persistent action

---

helm-projectile.el

Address #64.
Fundamentally, the use of `coerce` and reliance on `helm-candidate-buffer` is the wrong thing to do. Instead, Helm source candidates should be `(DISPLAY . REAL)` pairs, where `DISPLAY` is the short file name and `REAL` is the full path.
cc @bbatsov

Display real

---

helm-projectile.el

Line truncation of helm buffers should be customize-able, IMHO. This simple straight-on approach uses a single variable for all helm commands in this package. It could probably be more advanced and I picture two alternative implementations:
1. A new (custom) variable for each helm command. This involves black magic in the `helm-projectile-command` macro which is way beyond my elisp knowledge.
2. A custom list of commands that should have truncation with a default fall-back (like the one implemented in this PR).

Make line truncation in helm buffers customizable.

---

helm-projectile.el

Pass ignored files from `.projectile` to `ag`

ignore "-dir/" from .projectile in helm-projectile-ag

---

helm-projectile.el

https://github.com/bbatsov/projectile/pull/1149 introduced
buffer-local caching of certain project variables, which in turn
has caused issues with other commands not working properly. One
example is https://github.com/bbatsov/projectile/pull/1151
When using `helm-projectile`, `helm-projectile-find-file` is broken
after switching buffers, because all helm commands are run in the
context of a global `helm-projectile` buffer, incorrect cache values
are return from functions like `(projectile-project-root)`
My particular issue has been that after switching to a new project, or
moving between windows, `helm-projectile-find-file` has opened helm
with a list of files from _the previous project._
I was able to fix this initially by adding
`(projectile-reset-cached-project-root)` into the …

Separate buffers for separate projects

---

helm-projectile.el

Fix #92
Swallowing errors can hide problems outside of (Helm-)Projectile.
In any case, it's better to show the user an error message than to present a blank Helm buffer.

Avoid swallowing errors

---

helm-projectile.el

This PR should fix the issue: https://github.com/bbatsov/helm-projectile/issues/109
Turns out the old code never uses the options argument.

`helm-projectile-ag` passes options to helm-do-ag

---

helm-projectile.el

This fixes a bug when trying to use `helm-source-projectile-recentf-list` as a source for helm. This uses the same fix introduced by 6e881c824a01251a866e5070980cb25ca5b0dc66 to fix #98

Recentf source returns nil instead of error when not in project

---

helm-projectile.el

project-get-other-files now only takes two arguments. Change was in https://github.com/bbatsov/projectile/pull/1394

Fix for change in project-get-other-files signature

---

helm-projectile.el

Include paths to keep and ensure specified in `.projectile`.

[GH-124] Properly set `helm-ag` targets

---

helm-projectile.el

Per the documentation for declare-function, functions in external
packages should be prefaced with "ext:".
----
#

Add "ext:" to functions in external packages

---

helm-projectile.el

This is especially useful in the case of the git grep command where it is often desirable to recurse into submodules with something like
```git --no-pager grep --recurse-submodules --no-color -n%c -e %p -- %f```
This fixes #134

Allow customization of grep commands.

---

CHANGELOG.md
helm-projectile.el

Use `helm-projectile` interface immediately after switching to a project with `helm-projectile-switch-project`.
This is a very small change, in addition to the file listing shown before, it gives the user their project buffers and recentf as sources after switching projects. It's the same interface but a little more convenient.
Closes #142
:question: The commits are consistent with our [contribution guidelines](../blob/master/CONTRIBUTING.md)

Use helm-projectile in switch to project action

---

CHANGELOG.md
helm-projectile.el

`helm-ff-switch-to-eshell` is not defined, but
`helm-ff-switch-to-shell` is. By default, it uses Eshell.
An alternative is to keep `helm-projectile-switch-to-eshell`'s name unchanged and simply change the two lines where `helm-ff-switch-to-eshell` (which doesn't exist) is invoked.
Thanks!

Rename helm-projectile-switch-to-eshell -> helm-projectile-switch-to-shell

---

README.md

> apt is a high-level command-line interface for better interactive usage
according to https://salsa.debian.org/apt-team/apt the README.md file of apt-get and apt.

Change apt-get to apt in README.md

---

CHANGELOG.md
helm-projectile.el

Teach helm-projectile-rg to ignore the Projectile ignored files and directories lists.
Thanks!

teach helm-projectile-rg to respect projectile-ignored-files etc.

---

helm-projectile.el

According to the
https://www.gnu.org/software/emacs/manual/html_node/elisp/Composite-Types.html
`list` is a composite type and should be used when the number of
elements and its types are known. For `helm-projectile-sources-list` the
better option would be `(repeat symbol)`.
emacs-29 introduces `setopt` macro to set customizable variables, it
verifies variable type according to `:type` annotation and throw an
error if type mismatches.
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!

Fix type for helm-projectile-sources-list variable

---

CHANGELOG.md
helm-projectile.el

Sometimes, the first element in `projectile-project-buffer-names` is not actually a current buffer so just replace `(cdr ...` with `(remove (buffer-name) ...`.
Fixes #176
Thanks!

Correctly remove current buffer from helm-source-projectile-buffers-list

---

CHANGELOG.md
helm-projectile.el

Improve `helm-source-proctile-project-list` by also inheriting the `helm-type-file` class to benefit of it's functionality
such as candidate transformer or file cache.

Improve projectile project list

---

helm-projectile.el

I am not sure if this is the correct way to fix, yet this workaround seems to
work in my case. I had very similar observations as others claimed in #185 when
trying to debug this issue. Namely, right after executing
`helm-projectile-swithc-project` I observed that `projectile-known-projects`
had names changed with fontification.
Fixes #185

Deep copy list of known projects to avoid helm adding faces

---

CHANGELOG.md
helm-projectile.el

New defcustom that when set to 'projectile', will compute ignores and explicitely add additionally command line arguments to the search tool. Note that this might override search tool specific behaviors (for instance ag would not use VCS ignore files).

Introduce helm-projectile-ignore-strategy, closes #58

---

CHANGELOG.md
helm-projectile.el

Update slots specific to `helm-projectile-projects-source` that are overwritten
by `helm-type-files`. The goal is to get back functionality, that has been
changed with #181.
I think that the biggest miss is the lack of `helm-projectile-projects-map`
resulting in inability to instantaneously run things like `magit-status` for
a project.
I also have taken a liberty and updated modeline to display, in my opinion,
more suitable "Project(s)" (instead of "File(s)").
Thanks!

Fix helm-projectile-projects-source slots

---

helm-projectile.el

The `helm-ag` has been removed from MELPA
https://github.com/melpa/melpa/pull/9520, with a recommendation to use a Helm
built-in `helm-grep-ag`.
Please see individual commits for detailed explanation, including list of
things that has changed due to different implementations.
I decided to split this into two commits, as the population of input may be
changed in a future ant this commit may be reverted (or at least serve as a
guideline for the manual reversion).
fixes: #193
Thanks!

Switch  to use built-in `helm-grep-ag`

---

CHANGELOG.md
helm-projectile.el

N.B. This work is a re-implementation of #173 by @samertm from a few years
back. I can confirm that `helm-projectile` still suffers from the condition,
and that the fix works. Unfortunately, I cannot push to the original branch,
hence the new PR.
Closes: #173
Below, please find text from the original PR.
Don't overwrite helm-buffer-max-length when it's nil, because nil
indicates that we should use the max length of the longest file every
time.
This code is now the same as what helm-buffers does:
https://github.com/emacs-helm/helm/blob/8ed0ab7762ad76da02d8832aa18d03e1288ea6d5/helm-buffers.el#L300
Thanks!

Respect helm-buffer-max-length if it's nil

---

CHANGELOG.md
helm-projectile.el

closes #189 
a few things were wrong here: 
1. Previously the code setting `helm-rg--extra-args` was de-duping the "--glob" literal resulting in a non-parsable set of args.
2. The `grep-find-ignored-files` often contains string like `*.ext` which would unfortunately get escaped by the `glob-quote` utility.
3. The previous code would concat these together as a single string, which helm-rg doesn't expect
This patch addresses both of these.
Thanks!

Fix `helm-rg--extra-args` failing to provide valid globs
